
message(STATUS " CPACK_PROJECT_NAME ${PROJECT_NAME}")
message(STATUS " CPACK_PROJECT_VERSION ${PROJECT_VERSION}")

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
